services:
  # ----------------------------------------
  # 1. THE DATABASE ENGINE (PostgreSQL)
  # ----------------------------------------
  postgres_db:
    image: postgres:16
    container_name: my_learning_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bid_project_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - data_network

  # ----------------------------------------
  # 2. THE VISUAL INTERFACE (pgAdmin)
  # ----------------------------------------
  pgadmin_gui:
    image: dpage/pgadmin4
    container_name: my_learning_gui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      - data_network

  # 3. LE CONTENEUR PYTHON (Votre environnement isolé)
  etl_pipeline:
    build: .
    container_name: my_etl_pipeline
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    networks:
      - data_network

  # ----------------------------------------
  # 4. THE API SERVICE (FastAPI)
  # ----------------------------------------
  api_dashboard:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_dashboard
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    networks:
      - data_network

  # ----------------------------------------
  # 5. THE FRONTEND (React / TanStack)
  # ----------------------------------------
  frontend_dashboard:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_dashboard
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - api_dashboard
    networks:
      - data_network

# ----------------------------------------
# 6. THE HARD DRIVE (Volumes)
# ----------------------------------------
volumes:
  pgdata:

    # 7. LES ROUTES (Connexions entre conteneurs)
networks:
  data_network:
    driver: bridge
